### PR TITLE
Update eclipse-mylyn.jsonnet

### PR DESCRIPTION
**Pull request by merks**
Archive (make read-only) org.eclipse.mylyn.docs.

### CODE REVIEW

**Comment by merks** [comment]
@BeckerFrank  

Probably the repo should be read-only now that that is has been merged.

@ruspl-afed 

I wonder if there are any other repos that should be archived but have been overlooked as such?

**Comment by BeckerFrank** [comment]
> @BeckerFrank
> 
> Probably the repo should be read-only now that that is has been merged.

Yes the repository org.eclipse.mylyn.docs should archived.
What is needed to finish this Pull Request?

> 
> @ruspl-afed
> 
> I wonder if there are any other repos that should be archived but have been overlooked as such?

@akurtakov : should we also archive the following two Repositories?
- org.eclipse.mylyn.docs.intent.main
- org.eclipse.mylyn.docs.vex

**Comment by merks** [comment]
This needs to be merged by the foundation staff. They need a project lead to approve of doing that.

**Comment by netomi** [comment]
if you approve, we can merge that right away and apply the changes.

**Comment by merks** [comment]
Note that the attribute can be removed in the future so it’s not a problem to mark something archived and the change your mind later. 

Best to archive other things via a separate PR.  I just wanted folks to consider it.

**Review by BeckerFrank — APPROVED** [review]
LGTM

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
change is live.

**Pull request merged**
